services:
  kong:
    image: kong:3.5
    restart: unless-stopped
    user: kong
    environment:
      KONG_DATABASE: off
      KONG_DECLARATIVE_CONFIG: /kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
      KONG_STATUS_LISTEN: 0.0.0.0:8100
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
      - "8100:8100"
    volumes:
      - ./config/kong.yml:/kong/declarative/kong.yml:ro
    depends_on:
      httpbin:
        condition: service_started
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 5s
      retries: 10

  httpbin:
    image: kennethreitz/httpbin
    restart: unless-stopped
    expose:
      - "80"

networks:
  default:
    name: kong-study-db-less
    driver: bridge
